name: Deploy
on:
  push:
    branches:
      - deploy
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions@v1
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: "deploy --build-arg ACCESS_TOKEN_GITHUB=${{ secrets.ACCESS_TOKEN_GITHUB }}"
